### ISSUE TITLE
Добавить Titel к социальным сетям

### ISSUE THREAD

**Issue by joomline** [Arkadiy-Sedelnikov/slogin#13]
хочу предложить еще одно улучшение. мелочь, а приятно.
в файле modules/mod_slogin/tmpl/compact.php
есть строка:
            <a href="<?php echo JRoute::_($link['link']);?>"><span class="<?php echo $link['class'];?>">&nbsp;</span></a>

её можно улучшить добавив title в элемент "a", на форме так будет смотреться более человечнее
вот мой вариант:
<a href="<?php echo JRoute::_($link['link']);?>" title='<?php echo JText::_('MOD_SLOGIN_'. StrToUpper($link['plugin_name']))?>'><span class="<?php echo $link['class'];?>">&nbsp;</span></a>

А переводы добавить в файлы с языками

MOD_SLOGIN_FACEBOOK="Фейсбук"
MOD_SLOGIN_VKONTAKTE="Вконтакте"
MOD_SLOGIN_ODNOKLASSNIKI="Одноклассники"
MOD_SLOGIN_MAIL="Mail.ru - Мой мир"
MOD_SLOGIN_YANDEX="Яндекс"
MOD_SLOGIN_GOOGLE="Гугл плюс"
MOD_SLOGIN_LINKEDIN="LinkedIn"
MOD_SLOGIN_LIVE="Live.com"
MOD_SLOGIN_TWITTER="Twitter"

MOD_SLOGIN_FACEBOOK="Facebook"
MOD_SLOGIN_VKONTAKTE="Vkontakte"
MOD_SLOGIN_ODNOKLASSNIKI="Odnoklassniki.ru"
MOD_SLOGIN_MAIL="Mail.ru"
MOD_SLOGIN_YANDEX="Yandex.ru"
MOD_SLOGIN_GOOGLE="Google plus"
MOD_SLOGIN_LINKEDIN="LinkedIn"
MOD_SLOGIN_LIVE="Live.com"
MOD_SLOGIN_TWITTER="Twitter"

**Comment by Arkadiy-Sedelnikov** [comment]
Сделал.
