### ISSUE TITLE
Seo оптимизация Slogin

### ISSUE THREAD

**Issue by joomline** [Arkadiy-Sedelnikov/slogin#29]
Сейчас ссылка генерируется в Slogin вот так.
http://mc-class.ru/component/slogin/provider/wordpress/auth/aW5kZXgucGhwP0l0ZW1pZD0yMQ==.html
Эксперименты показывают, что даже если ее закрыть через robots.txt или подгружать аяксом google индексирует эту ссылку.
Предлагаю внести правки в код компонента и скрыть постоянно изменяющиеся окончания ссылок.

**Comment by Arkadiy-Sedelnikov** [comment]
389440df220b94ded5747d76169258a69ac0d823
