### ISSUE TITLE
Не корректное заполнение полей при выбранной настройке "Редактировать данные перед регистрацией"

### ISSUE THREAD

**Issue by joomline** [Arkadiy-Sedelnikov/slogin#54]
Если активировать настройку "Редактировать данные перед регистрацией"
Полные настройки вот такие:
http://prntscr.com/62qc50

То после авторизации через социальную сеть будет вот такая картинка:
http://prntscr.com/62qbl4

Что здесь не так:
Не заполнено поле "имя"
И логин указан не корректно, требуется указывать е-меил так как в настройках задан е-меил.

**Comment by Arkadiy-Sedelnikov** [comment]
9cd7596c84802c331dfb154b786e09b9275400c5
