### ISSUE TITLE
Failed redirection on facebook login.

### ISSUE THREAD

**Issue by Timekiller11** [Arkadiy-Sedelnikov/slogin#57]
Can be resolved by changing : 
 $redirect = JRoute::_(base64_decode($session->get('slogin_return', '')));

to

  $redirect = JRoute::_(base64_decode($session->get('slogin_return', '')), false);

in com_slogin/controller.php Line 452

**Comment by Arkadiy-Sedelnikov** [comment]
ab519d4cc5403b878bff5fc60e2852ed23ed7fe5
