### ISSUE TITLE
Проблема с редактированием данных при создании нового аккаунта

### ISSUE THREAD

**Issue by joomline** [Arkadiy-Sedelnikov/slogin#58]
Работает отлично за исключением нюанса:
Когда первый раз авторизуюсь через соц. сеть, то возникает окно с тремя полями:
- Имя (например: Kirill)
- Логин (например: Kirill-Fedorov-vkontakte) - Я не могу сменить логин, даже если я его меняю на другой, то все равно остается именно этот
- Email (например: kirill_fedorov@mail.ru

**Comment by Arkadiy-Sedelnikov** [comment]
33e209226073bc4cc645b5c83aefefd66d661b7f
