### ISSUE TITLE
открытие старого окна авторизации социальной сети.

### ISSUE THREAD

**Issue by joomline** [Arkadiy-Sedelnikov/slogin#63]
Если не закончить авторизацию через социальную сеть, и попробовать авторизоваться через другую сеть, будет открыто окно первой социальной сети.
http://joomline.net/ru/forum/slogin/5642-redirect-na-stranitsu-sots-seti-kotoruyu-otkryval-i-zakryl.html

**Comment by Arkadiy-Sedelnikov** [comment]
Сделано
